# Generated by Django 5.0.3 on 2024-07-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
