# Generated by Django 5.0.3 on 2024-07-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_text_comment_content_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
